New russian translation

diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -8,6 +8,25 @@ cd $( dirname $realpath)/..
 
 [ -e config/server.sh ] && source config/server.sh
 
+function init_public
+# Create all dynamically generated files in public/ folder
+{
+    bundle exec thin \
+         -d --pid log/thin.pid --address localhost --port $THIN_PORT \
+         start
+    for ((i = 0; i < 20; i += 1)) do
+        sleep 2
+        wget -q -O tmp/server.html http://localhost:$THIN_PORT && \
+            rm tmp/server.html && break
+    done
+    bundle exec thin --pid log/thin.pid stop
+    if [ -e tmp/server.html ]; then
+        echo "Cannot get index.html from web server (aborted)" >&2
+        return 2
+    fi
+    bundle exec jammit
+}
+
 # Scan for -p, find out what port thin is about to use.
 args="$DEFAULT_THIN_ARGS $@"
 prev_arg=''
@@ -48,7 +67,20 @@ if [ ! -e public/source.tar.gz ]; then
     exit 65
 fi
 
+# Precache jammit assets
+if [[ -w public  && ! -e public/stylesheets/application.css ]]; then
+    if [ "$INIT_PUBLIC" != 'no' ]; then
+        echo "Making first-time server initialization."
+        init_public
+    fi
+fi
+if [ ! -e 'public/assets/main.js.gz' ]; then
+    echo 'Jammit precache error (now or at install)' >&2
+    exit 66
+fi
+
+
 mkdir -p -v log/thin/
 bundle exec ruby ./script/websocket_server.rb&
-bundle exec magent start -d --log-path=log/
+bundle exec magent start --log-path=log/ &
 bundle exec thin start $args
